### ISSUE TITLE
make your addon working for all web pages

### ISSUE THREAD

**Issue by rinaldi6109** [PyvesB/NightVideoTuner#1]
Your addon is wonderful but I would like to see it working not only for videos but even for whole web pages. Is it possible?

**Comment by PyvesB** [comment]
Hello @rinaldi6109, thanks for your interest in the project! The extension uses [CSS filters](https://developer.mozilla.org/docs/Web/CSS/filter) underneath the hood. These are usually applied to graphical elements, I'm wondering how browsers would behave if they were applied to the whole HTML page. Though, I've got the feeling this would be somewhat out of scope, after all the extension is branded as a "video tuner"! 😄
